.TH CHIP8DISASM 1 "March 2018" "version 0.1.0"
.SH NAME
chip8disasm \- disassemble Chip\-8 binaries
.SH SYNOPSIS
.B chip8disasm
[(\fB\-o\fR|\fB\-\-output\fR) \fIOUTPUT\fR]
[\fB\-q\fR|\fB\-\-shift\-quirks\fR]
[\fB\-v\fR|\fB\-\-verbose\fR]
[\fB\-h\fR|\fB\-\-help\fR]
[\fB\-V\fR|\fB\-\-version\fR]
.I FILE
.SH DESCRIPTION
.B chip8disasm
is a disassembler for Chip\-8 binaries which produces output in the syntax used
by
.BR chip8asm (1).
.PP
\fBchip8disasm\fR uses a primitive form of control-flow analysis to determine
which sections of the input are data and which are code.
.
The method used should be sufficient for all "normal" input; it is possible,
however, to intentionally obfuscate binaries using self-modifying code so that
they cannot be properly disassembled.
.
The reference manual provided with the Chip\-8 project contains a more detailed
description of the process used.
.PP
Games which use the two-argument forms of the SHL and SHR instructions will
need to be processed in "shift quirks" mode, or the disassembled output will
contain invalid instructions.
.SH OPTIONS
.TP
.BR \-o ", " \-\-output =\fIOUTPUT\fR
Set the output file name.
.
If no output file name is specified or is \fI-\fR, then the disassembled output
will be printed to the standard output.
.TP
.BR \-q ", " \-\-shift\-quirks
Enable shift quirks mode.
.TP
.BR \-v ", " \-\-verbose
Increase verbosity.
.
Each repetition of this flag will enable an additional level of logging output.
.
In order of decreasing severity, the log levels are ERROR, WARNING, INFO and
DEBUG.
.
By default, only messages at the ERROR and WARNING levels are shown.
.TP
.BR \-h ", " \-\-help
Show a brief help message and exit.
.TP
.BR \-V ", " \-\-version
Show version information and exit.
.SH SEE ALSO
.BR chip8 (1),
.BR chip8asm (1)
