.Dd March 9, 2018
.Dt CHIP8 1
.Os
.Sh NAME
.Nm chip8
.Nd emulate the Chip\-8 and Super\-Chip platforms
.Sh SYNOPSIS
.Nm
.Op Fl hlqVv
.Op Fl f Ar freq
.Op Fl s Ar scale
.Op Fl t Ar tone
.Op Fl u Ar volume
.Op Ar file
.Sh DESCRIPTION
.Nm
emulates the Chip\-8 and Super\-Chip platforms.
It accepts one operand, the game file to execute.
The arguments are as follows:
.Bl -tag -width Ds
.It Fl f Ns , Fl \-frequency Ns = Ns Ar freq
Set the game timer frequency (in Hz).
Default is 60.
.It Fl h Ns , Fl \-help
Show a brief help message and exit.
.It Fl l Ns , Fl \-load\-quirks
Enable load quirks mode.
.It Fl q Ns , Fl \-shift\-quirks
Enable shift quirks mode.
.It Fl s Ar scale Ns , Fl \-scale Ns = Ns Ar scale
Set game display scale.
Default is 6.
In high-resolution (Super\-Chip) mode, the emulator will display each in-game
pixel as
.Ar scale
square pixels on the user's display.
In low-resolution (Chip\-8) mode, the
.Ar scale
parameter is effectively doubled, so that the emulator window will be the same
size as if it were displaying high-resolution content.
.It Fl t Ar freq Ns , Fl \-tone Ns = Ns Ar freq
Set game buzzer tone (in Hz).
Default is 440.
The sound capabilities of the Chip\-8 are limited to a single, monotone pitch,
which in this implementation is a square wave.
.It Fl u Ar volume Ns , Fl \-volume Ns = Ns Ar volume
Set game sound volume, from 0 to 100.
Default is 10.
.It Fl V Ns , Fl \-version
Show version information and exit.
.It Fl v Ns , Fl \-verbose
Increase verbosity.
Each repetition of this flag will enable an additional level of logging output.
In order of decreasing severity, the log levels are ERROR, WARNING, INFO and
DEBUG.
By default, only messages at the ERROR and WARNING levels are shown.
.El
.Sh SEE ALSO
.Xr chip8asm 1 ,
.Xr chip8disasm 1
