.Dd March 9, 2018
.Dt CHIP8ASM 1
.Os
.Sh NAME
.Nm chip8asm
.Nd assemble Chip\-8 source files
.Sh SYNOPSIS
.Nm
.Op Fl hqVv
.Op Fl o Ar output
.Op Ar file
.Sh DESCRIPTION
.Nm
is an assembler for the Chip\-8 and Super\-Chip, with a syntax close to that
used by the popular CHIPPER assembler.
The arguments are as follows:
.Bl -tag -width Ds
.It Fl h Ns , Fl \-help
Show a brief help message and exit.
.It Fl o Ar output Ns , Fl \-output Ns = Ns Ar output
Set the output file name.
If no output file name is specified, one will be deduced from the input file
name by replacing the file extension with .bin.
When the input file is \- (standard input), the output will be printed to the
standard output.
.It Fl q Ns , Fl \-shift\-quirks
Enable shift quirks mode.
.It Fl V Ns , Fl \-version
Show version information and exit.
.It Fl v Ns , Fl \-verbose
Increase verbosity.
Each repetition of this flag will enable an additional level of logging output.
In order of decreasing severity, the log levels are ERROR, WARNING, INFO and
DEBUG.
By default, only messages at the ERROR and WARNING levels are shown.
.El
.Sh SEE ALSO
.Xr chip8 1 ,
.Xr chip8disasm 1
