image: debian:latest

stages:
  - build
  - test

before_script:
  - apt-get update -y
  - apt-get install -y gcc meson libsdl2-dev texinfo

build:
  stage: build
  script:
    - mkdir build && cd build
    - meson
    - ninja

test:
  stage: test
  script:
    - ninja test
