image: debian

stages:
  - build
  - test

before_script:
  - apt-get update -y
  - apt-get install -y gcc meson libsdl2-dev texinfo

build:
  stage: build
  script:
    - mkdir build && cd build
    - meson
    - ninja
    - ninja info/chip8.info
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - cd build
    - ninja test
  dependencies:
    - build
