language: c

addons:
  apt:
    packages:
      - ninja-build
      - python3-pip
      - texinfo

install:
  - pip3 install meson

script:
  - meson -Db_sanitize=address build
  - ninja -C build
  - ninja -C build info/chip8.info
  - ninja -C build test
