language: c
sudo: enabled

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y meson libsdl2-dev texinfo

script:
  - mkdir build && cd build
  - meson -Db_sanitize=address
  - ninja
  - ninja info/chip8.info
  - ninja test
