language: c
sudo: required

services:
  - docker

install:
  - docker build -t ianprime0509/chip8-ci .

script:
  - docker run --name ci -it -d ianprime0509/chip8-ci /bin/bash
  - docker ps -a
  - docker exec -it ci mkdir build && meson -Db_sanitize=address build
  - docker exec -it ci ninja -C build
  - docker exec -it ci ninja -C build info/chip8.info
  - docker exec -it ci ninja -C build test
