language: c
sudo: required

services:
  - docker

install:
  - docker build -t ianprime0509/chip8-ci .

script:
  - docker run --name ci -it -d ianprime0509/chip8-ci /bin/bash
  - docker ps -a
  - docker exec -it ci meson --version
  - docker exec -it ci mkdir build
  - docker exec -it ci meson -Db_sanitize=address build
  - docker exec -it ci ninja -C build
  - docker exec -it ci ninja -C build info/chip8.info
  - docker exec -it ci ninja -C build info/html
  - docker exec -it ci ninja -C build test
  - docker cp ci:build/info/html ./docs

deploy:
  provider: pages
  local-dir: docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
