language: c
sudo: required

addons:
  apt:
    packages:
      - ninja-build
      - python3-pip
      - texinfo

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ninja-build python3-pip texinfo
  - sudo pip3 install meson

script:
  - meson -Db_sanitize=address build
  - ninja -C build
  - ninja -C build info/chip8.info
  - ninja -C build test
