#+TITLE: README for Chip-8

This is a [[https://en.wikipedia.org/wiki/CHIP-8][Chip-8]] emulator, written in C.  Currently, all the Chip-8 games I
have tested are functional, and some Super-Chip games are as well (in
particular, BLINKY).  Many Super-Chip games don't quite work yet, though.

The main documentation for the project is its manual, which is generated by GNU
Texinfo during the default build process (it will be in the ~info~ subdirectory
of your build directory; see below for build instructions).

* Building

You can build the project using the following commands (the leading ~$~ is your
prompt):

#+BEGIN_SRC sh
  $ mkdir build && cd build
  $ meson
  $ ninja
#+END_SRC

The executable binaries will be located in ~build/src~.  Then, you can run
~ninja info/chip8.info~ to build the manual in info format.

If you get an error about ~texi2any~ not being available, that means you don't
have GNU Texinfo installed and won't be able to build the manual.  You can
either install it, or run ~meson configure -Dtexinfo=false~ in the build
directory to ignore it.  Additionally, if you have Doxygen installed and you
want some code documentation to be generated, you can run ~meson configure
-Ddocumentation=true~ before running ~ninja~.
